name: Sanidade do Terraform (CI)

on:
  push:
    branches:
      - main

jobs:
  validar-codigo:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Instalar o Terraform na máquina do GitHub
        uses: hashicorp/setup-terraform@v3

      - name: Checar formatação (terraform fmt)
        run: terraform fmt -check

      - name: Iniciar Terraform sem conectar na AWS
        run: terraform init -backend=false

      - name: Validar a sintaxe (terraform validate)
        run: terraform validate